"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
#coding: utf-8

from setuptools import setup

APP = ['mainchangefirend.py']
APP_NAME="Roy'sTools"
DATA_FILES = ['app.icns']
OPTIONS = {
	'argv_emulation':True,
	'iconfile':'app.icns',
	'plist': {
						'CFBundleName': APP_NAME,
						'CFBundleDisplayName': APP_NAME,
						'CFBundleGetInfoString': "Change something",
						'CFBundleIdentifier': "com.farewell.osx.roy'stools",
						'CFBundleVersion': "1.0.0",
						'CFBundleShortVersionString': "1.0",
						'NSHumanReadableCopyright': u"Copyright 2017,Roy,Rights Reserved"
					}
				}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
